{
  format: 'json',
  _order: [ { key: 'format', value: 'json', from: 'argv' } ],
  _args: [ 'https://api.github.com/users/matt-ramotar' ]
}
{
  login: 'matt-ramotar',
  id: 59468153,
  node_id: 'MDQ6VXNlcjU5NDY4MTUz',
  avatar_url: 'https://avatars3.githubusercontent.com/u/59468153?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/matt-ramotar',
  html_url: 'https://github.com/matt-ramotar',
  followers_url: 'https://api.github.com/users/matt-ramotar/followers',
  following_url: 'https://api.github.com/users/matt-ramotar/following{/other_user}',
  gists_url: 'https://api.github.com/users/matt-ramotar/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/matt-ramotar/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/matt-ramotar/subscriptions',
  organizations_url: 'https://api.github.com/users/matt-ramotar/orgs',
  repos_url: 'https://api.github.com/users/matt-ramotar/repos',
  events_url: 'https://api.github.com/users/matt-ramotar/events{/privacy}',
  received_events_url: 'https://api.github.com/users/matt-ramotar/received_events',
  type: 'User',
  site_admin: false,
  name: null,
  company: null,
  blog: '',
  location: 'Boston, MA',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 1,
  public_gists: 0,
  followers: 5,
  following: 5,
  created_at: '2020-01-03T07:40:17Z',
  updated_at: '2020-06-23T15:48:25Z'
}
